### ISSUE TITLE
Recipe Tester UX/UI

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#1043]
## Summary

Recipe testing app for pylons SDK game developers

## Problem Definition

We need a developer tool that helps game developers test recipes they've created using our sdk recipe creator

## Proposal

single UI that let's users:
1. Obtain their item inventory from their Pylons Wallet
2. Ingest recipes they've created
3. Test recipes using items in their inventory to see what happens

![Screen Shot 2022-09-13 at 3 57 22 PM](https://user-images.githubusercontent.com/97635071/189997243-092c939b-c15a-4367-89cf-b84b2607078b.png)

Figma link: https://www.figma.com/file/EjpUsKHbvKyzNFJzRcxKUw/Recipe-Test-UI?node-id=25%3A2
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by MikeSofaer** [comment]
@afti-githobo hopefully this gives you stuff to work on while we get the SDK fixed up

**Comment by afti-githobo** [comment]
I'm a little confused by what this is supposed to be. Is it something *specific,* or is it a general-purpose app for running arbitrary recipes?

If the latter: that's good and we should have it, but I definitely can't implement this UI as-is, because it's assuming things about the structure of items and the meaning of state changes that we can't assume. Like, we can't have a neat tabbed inventory setup like that if items are arbitrary, b/c it's down to the developer to decide how many categories and subcategories of items they're making, how they're distinguished from each other, how they're related, etc.

What we'd probably have to do instead would be to tab items by cookbook and then have some sort of custom filter setup for subcategories. We also aren't going to be able to have nice, context-rich state comparisons, for much the same reason - we cannot programmatically understand what the outputs of a recipe *mean.* We have to just have dumb a/b comparisons.

This is all fine, of course; I just wanna make sure we're on the same page.

**Comment by MikeSofaer** [comment]
It's supposed to be as general-purpose as possible, but it will of course require some customization.

One thing I think is that it probably doesn't need to have nice UX for switching cookbooks. Maybe a hidden menu somewhere but we don't need tabs or anything, it's primarily a single-cookbook view.

Initially I would put the cookbook ID and what item filters exist in a JSON file and start there. There's a temptation of having a system that turns item constraints into english and filters, but for now let's avoid that, and get something built that just gives the conditions as they are and then see what we want to add.

**Comment by afti-githobo** [comment]
> It's supposed to be as general-purpose as possible, but it will of course require some customization.
> 
> One thing I think is that it probably doesn't need to have nice UX for switching cookbooks. Maybe a hidden menu somewhere but we don't need tabs or anything, it's primarily a single-cookbook view.
> 
> Initially I would put the cookbook ID and what item filters exist in a JSON file and start there. There's a temptation of having a system that turns item constraints into english and filters, but for now let's avoid that, and get something built that just gives the conditions as they are and then see what we want to add.

Hmm. Been thinking about this and about ways to integrate it w/ the API revision work, and I have a proposal I want to make:

a) the recipe tester targets desktop platforms in addition to mobile. This is obviously a lower-friction setup for external development, and Flutter supports desktop builds anyway.
b) the recipe tester is developed *in tandem* with a newer, higher-abstraction version of the API for the Dart SDK. (API2) I should be able to build out a provisional desktop implementation of this along the same principles the Golang version of testapp uses without too much difficulty; it won't be as nice an experience as working with the mobile wallet, but it'll make Flutter development a lot easier, since you won't have to be pushing every single build to a handset or an emulator.
c) when API2 is ready and the recipe tester is functioning in some form on top of it, we begin to migrate the mobile codepaths onto it so we can get a mobile version of the recipe tester online. It would also be desirable to migrate Easel and Evently to API2 around this point so that we could fully drop API1.

**Comment by MikeSofaer** [comment]
This seems good, I think. Let's see what @kjawadDeveloper2 thinks.

**Comment by StefanB90** [comment]
may be a good idea if the chain tells you what happened with an executed recipe

**Comment by afti-githobo** [comment]
I have a working branch (cf. #1091) I've been doing frontend stuff on, but I'm really not satisfied w/ my progress on it. I'm not comfortable at all with Flutter UI stuff yet; I struggle to visualize what I'm trying to do with the tools, and I don't feel like I have a robust understanding of the best way to solve problems.

I have a few questions - first off, what's our due-by on this?

Second is more procedural - I'm significantly better at implementing business logic than I am at putting together a GUI w/ a toolset like Flutter. I've been trying to get the UI assembled before I start building the business logic here, but this means that at present all progress on this project is stalled while I'm doing things I'm bad at badly. I would like to shift gears from trying to build the UI for this thing out first to just implementing the business logic under a gross placeholder UI that conveys the necessary information? Either I or someone else could move onto UI fixes once an ugly prototype was in place and working, as appropriate; as-is, I'm not actually making any progress on the parts of this project that involve novel problems because I'm just farting around trying to figure out how to put the UI together.

Sorry about this; I'm kinda stressed out right now because that draft PR sucks and I know it sucks. Right now, I'm moving super slowly and there's no good reason for it. I'm just not good at the work. If I can quit worrying about getting the UI layout right for the moment I can refocus on the parts of this project I actually feel comfortable with, and then when the time comes to fix the UI I can do that on top of an application that basically works instead of trying to do the entire thing whole-cloth.

**Comment by MikeSofaer** [comment]
Ok, it's fine to focus on the business logic stuff for now. It also might make sense to pair with @Amean for the week, that could also help her get the widget shipped, and she could help you get the UX stuff done a little quicker.
