### ISSUE TITLE
When User is Purchasing Video NFT- Hovering Transparent over Box Buy Button 

### ISSUE THREAD

**Issue by Tanyaml** [Pylons-tech/pylons#897]
## Summary of Bug
When User is Purchasing Video NFT- Hovering Transparent over Box Buy Button for the first 30 seconds and disappears.
There should be no hovering transparent box over the actual Buy button.
Please see video and Screenshots:

https://user-images.githubusercontent.com/93543576/186929048-d65fddf2-4b39-47e4-95ab-c400909f5f99.mov

 

<img width="491" alt="Hovering box over buy button " src="https://user-images.githubusercontent.com/93543576/186929157-7e0c4742-3300-455b-a502-80f2f8ebfe65.png">

<img width="424" alt="Video NFT Hovering Box " src="https://user-images.githubusercontent.com/93543576/186930451-9a2aec03-fe7c-4036-bec0-99d96feda88a.png">

## Steps to Reproduce
1.User clicks on shared NFT to purchase and is directed to Pylons App
https://wallet.pylons.tech/?recipe_id=Easel_Recipe_auto_recipe_2022_08_25_222758_109&cookbook_id=Easel_CookBook_auto_cookbook_2022_08_25_222753_679&address=pylo1gqp0uxm0xwnlyfn5ma8hvg846mzxc3swqaawqw
2. User lands on NFT in pylons app and can view the box hovering over the buy button.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faizhashmiRnS** [comment]
Hi @Tanyaml, Can you please test it on some other video too?

Actually the video you used was a screen recording video of a video. So it opened the media controls for the video and they gone, while they were being recorded.
Our Buy button has a minor glass effect as per the provided design. That's why it seemed to have a transparent effect for a while because it had media controls at the back for a second. If all that makes sense.

Please ping me on discord. if it stills needs some fix.

**Comment by StefanB90** [comment]
@Tanyaml tested. Working as expected. This can be closed.
